function(add_example name)
    add_executable(${name} ${name}.cpp)
    target_link_libraries(${name} PRIVATE qf)
    target_include_directories(${name} PRIVATE ${CMAKE_SOURCE_DIR}/include)
endfunction()

add_example(bond_pricing)
add_example(yield_curve)
add_example(black_scholes)
add_example(monte_carlo)
add_example(finite_difference_models)
add_example(heston)
add_example(interest_rate_models)
add_example(swap_pricing)
